{
	"title": "referencing multiple datasets throws InsightError",
	"input": {
		"WHERE": {
			"GT": {
				"sections2_avg": 97
			}
		},
		"OPTIONS": {
			"COLUMNS": [
				"sections_dept",
				"sections_avg"
			]
		}
	},
	"errorExpected": true,
	"expected": "InsightError"
}